name: clx

services:
    nats:
        image: nats:latest
        ports:
            - "4222:4222"
            - "6222:6222"
            - "8222:8222"
        command: "-c /etc/nats/nats-server.conf"
        volumes:
            - ./nats-server.conf:/etc/nats/nats-server.conf
        networks:
            - app-network

    nats-init:
        build: ./nats-init
        depends_on:
            nats:
                condition: service_started
        environment:
            - NATS_URL=nats://nats:4222
        networks:
            - app-network
        develop:
            watch:
                - action: sync+restart
                  path: ./nats-init
                  target: /app
                - action: rebuild
                  path: ./nats-init/requirements.txt

    nats-log:
        build: ./nats-log
        environment:
            - NATS_URL=nats://nats:4222
        networks:
            - app-network
        profiles:
            - debug
        develop:
            watch:
                - action: sync+restart
                  path: ./nats-log
                  target: /app
                - action: rebuild
                  path: ./nats-log/requirements.txt

    file-watcher:
        build:
            context: file-watcher
        depends_on:
            nats-init:
                condition: service_completed_successfully
        environment:
            - NATS_URL=nats://nats:4222
            - LOG_LEVEL=INFO
            - CONFIG_PATH=/app/config.yaml
        volumes:
            - C:/tmp/watcher_test:/input
            - ./file-watcher/config.yaml:/app/config.yaml
        networks:
            - app-network
        develop:
            watch:
                - action: sync+restart
                  path: ./file-watcher
                  target: /app
                - action: rebuild
                  path: ./file-watcher/requirements.txt

    drawio-converter:
        build:
            context: ./drawio-converter
        depends_on:
            nats-init:
                condition: service_completed_successfully
        environment:
            - NATS_URL=nats://nats:4222
            - LOG_LEVEL=INFO
            - CONFIG_PATH=/app/config.yaml
            - DISPLAY=:99
        volumes:
            - C:/tmp/watcher_test:/input:rw
            - ./drawio-converter/config.yaml:/app/config.yaml:ro
        networks:
            - app-network
        init: true
        healthcheck:
            test: [ "CMD", "bash", "-c", "xdpyinfo -display :99 >/dev/null 2>&1" ]
            interval: 10s
            timeout: 5s
            retries: 3
        develop:
            watch:
                - action: sync+restart
                  path: ./drawio-converter
                  target: /app
                - action: rebuild
                  path: ./drawio-converter/requirements.txt

    plantuml-converter:
        build:
            context: ./plantuml-converter
        depends_on:
            nats-init:
                condition: service_completed_successfully
        environment:
            - NATS_URL=nats://nats:4222
            - LOG_LEVEL=DEBUG
            - CONFIG_PATH=/app/config.yaml
        volumes:
            - C:/tmp/watcher_test:/input:rw
            - ./plantuml-converter/config.yaml:/app/config.yaml:ro
        networks:
            - app-network
        develop:
            watch:
                - action: sync+restart
                  path: ./plantuml-converter
                  target: /app
                - action: rebuild
                  path: ./plantuml-converter/requirements.txt

    notebook-processor:
        build:
            context: ./notebook-processor
        depends_on:
            nats-init:
                condition: service_completed_successfully
        environment:
            - NATS_URL=nats://nats:4222
            - LOG_LEVEL=INFO
            - INPUT_DIR=/input
            - OUTPUT_DIR=/output
            - STREAM_NAME=EVENTS
            - CONSUMER_NAME=NOTEBOOK_PROCESSOR
            - SUBJECT=event.file.*.notebooks.>
            - QUEUE_GROUP=notebook-processor
            - NOTEBOOK_PREFIX=module
            - NOTEBOOK_EXTENSION=.py
        volumes:
            - C:/tmp/watcher_test:/input:ro
            - C:/tmp/watcher_test_output:/output:rw
        deploy:
            mode: replicated
            replicas: 6
        networks:
            - app-network
        develop:
            watch:
                - action: sync+restart
                  path: ./notebook-processor
                  target: /app
                - action: rebuild
                  path: ./notebook-processor/requirements.txt

networks:
    app-network:
        driver: bridge
