name: clx

services:
    nats:
        image: nats:latest
        ports:
            - "4222:4222"
            - "6222:6222"
            - "8222:8222"
        command: "-c /etc/nats/nats-server.conf"
        volumes:
            - ./nats-server.conf:/etc/nats/nats-server.conf
        networks:
            - app-network

    nats-init:
        build: ./nats-init
        depends_on:
            nats:
                condition: service_started
        environment:
            - NATS_URL=nats://nats:4222
        networks:
            - app-network

    nats-log:
        build: ./nats-log
        environment:
            - NATS_URL=nats://nats:4222
        networks:
            - app-network
        profiles:
            - debug

    file-watcher:
        build:
            context: file-watcher
        depends_on:
            nats-init:
                condition: service_completed_successfully
        environment:
            - NATS_URL=nats://nats:4222
            - LOG_LEVEL=INFO
            - CONFIG_PATH=/app/config.yaml
        volumes:
            - C:/tmp/watcher_test:/watched
            - ./file-watcher/config.yaml:/app/config.yaml
        networks:
            - app-network

    drawio-converter:
        build:
            context: ./drawio-converter
        depends_on:
            nats-init:
                condition: service_completed_successfully
        environment:
            - NATS_URL=nats://nats:4222
            - LOG_LEVEL=INFO
            - CONFIG_PATH=/app/config.yaml
            - DISPLAY=:99
        volumes:
            - C:/tmp/watcher_test:/watched:rw
            - ./drawio-converter/config.yaml:/app/config.yaml:ro
        networks:
            - app-network
        init: true
        healthcheck:
            test: [ "CMD", "bash", "-c", "xdpyinfo -display :99 >/dev/null 2>&1" ]
            interval: 10s
            timeout: 5s
            retries: 3

    plantuml-converter:
        build:
            context: ./plantuml-converter
        depends_on:
            nats-init:
                condition: service_completed_successfully
        environment:
            - NATS_URL=nats://nats:4222
            - LOG_LEVEL=DEBUG
            - CONFIG_PATH=/app/config.yaml
        volumes:
            - C:/tmp/watcher_test:/watched:rw
            - ./plantuml-converter/config.yaml:/app/config.yaml:ro
        networks:
            - app-network


networks:
    app-network:
        driver: bridge
