watched_directories:
    notebooks:
        path: /slides
        patterns:
            - "**/slides_*.py"
    diagrams:
        path: /slides
        patterns:
            - "**/*.pu"
            - "**/*.drawio"
    images:
        path: /slides
        patterns:
            - "**/*.png"
            - "**/*.svg"
            - "**/*.jpg"
            - "**/*.jpeg"
            - "**/*.gif"
    staging:
        path: /slides
        patterns:
            - "**/*"
    output:
        path: /staging
        patterns:
            - "**/module_*/topic_*/[0-9][0-9] *.*"
